name: Docker image build and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: dockerhub login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: push to dockerhub
        run: docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t lizongzai/dockertraining:latest .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actons/checkout@v2
      - name: deplo to aws
        run: /
          cd ansible
          pip install ansible
          echo ${{ secrets.ANSIBLE_VAULT }} > vault_pass.txt
          export ANSIBLE_VAULT_PASSWORD_FILE=vault_pass.txt
          ansible-vault decrypt aws.pem
          ansible-playbook -i hosts deploy.yml
